/*
 * List Type
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'om.liferay.headless.admin.list.type.client', and version '1.0.0'.. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.list.type.client', and version '1.0.23'.
 *
 * The version of the OpenAPI document: v1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Facet {
    #[serde(rename = "facetCriteria", skip_serializing_if = "Option::is_none")]
    pub facet_criteria: Option<String>,
    #[serde(rename = "facetValues", skip_serializing_if = "Option::is_none")]
    pub facet_values: Option<Vec<crate::models::FacetValue>>,
}

impl Facet {
    pub fn new() -> Facet {
        Facet {
            facet_criteria: None,
            facet_values: None,
        }
    }
}

impl Default for Facet {
    fn default() -> Self {
        Self::new()
    }
}
