/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.61'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectFolderItem {
    #[serde(rename = "linkedObjectDefinition", skip_serializing_if = "Option::is_none")]
    pub linked_object_definition: Option<bool>,
    #[serde(rename = "objectDefinitionExternalReferenceCode", skip_serializing_if = "Option::is_none")]
    pub object_definition_external_reference_code: Option<String>,
    #[serde(rename = "positionX", skip_serializing_if = "Option::is_none")]
    pub position_x: Option<i32>,
    #[serde(rename = "positionY", skip_serializing_if = "Option::is_none")]
    pub position_y: Option<i32>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl ObjectFolderItem {
    pub fn new() -> ObjectFolderItem {
        ObjectFolderItem {
            linked_object_definition: None,
            object_definition_external_reference_code: None,
            position_x: None,
            position_y: None,
            x_class_name: None,
        }
    }
}


