/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.61'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectValidationRule {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "dateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "dateModified", skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<String>,
    #[serde(rename = "engine", skip_serializing_if = "Option::is_none")]
    pub engine: Option<String>,
    #[serde(rename = "engineLabel", skip_serializing_if = "Option::is_none")]
    pub engine_label: Option<String>,
    #[serde(rename = "errorLabel", skip_serializing_if = "Option::is_none")]
    pub error_label: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "externalReferenceCode", skip_serializing_if = "Option::is_none")]
    pub external_reference_code: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "objectDefinitionExternalReferenceCode", skip_serializing_if = "Option::is_none")]
    pub object_definition_external_reference_code: Option<String>,
    #[serde(rename = "objectDefinitionId", skip_serializing_if = "Option::is_none")]
    pub object_definition_id: Option<i64>,
    #[serde(rename = "objectValidationRuleSettings", skip_serializing_if = "Option::is_none")]
    pub object_validation_rule_settings: Option<Vec<crate::models::ObjectValidationRuleSetting>>,
    #[serde(rename = "outputType", skip_serializing_if = "Option::is_none")]
    pub output_type: Option<OutputType>,
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<bool>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl ObjectValidationRule {
    pub fn new() -> ObjectValidationRule {
        ObjectValidationRule {
            actions: None,
            active: None,
            date_created: None,
            date_modified: None,
            engine: None,
            engine_label: None,
            error_label: None,
            external_reference_code: None,
            id: None,
            name: None,
            object_definition_external_reference_code: None,
            object_definition_id: None,
            object_validation_rule_settings: None,
            output_type: None,
            script: None,
            system: None,
            x_class_name: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutputType {
    #[serde(rename = "fullValidation")]
    FullValidation,
    #[serde(rename = "partialValidation")]
    PartialValidation,
}

impl Default for OutputType {
    fn default() -> OutputType {
        Self::FullValidation
    }
}

